language: r
cache: packages

env:
  global:
    - ALLOWED_NOTES=2
    - NO_IMPORTS=4

notifications:
  email:
    recipients:
     - alerts@jumpingrivers.support
    on_success: change
    on_failure: change

before_install:
  - tlmgr install fancyvrb units
  - sudo apt-get install -y ghostscript
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/options.R && cat options.R >> ~/.Rprofile.site && rm -f options.R

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ $TRAVIS_BRANCH = "master" ]; then bash test_deploy.sh; fi
  - rm test_deploy.sh

script:
  - Rscript -e "source('https://raw.githubusercontent.com/jr-packages/drat/master/script.R')"

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
